-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 17:29:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `animals` ;

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animals` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `animals` ;

-- -----------------------------------------------------
-- Table `animals`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animals`.`animals` ;

CREATE TABLE IF NOT EXISTS `animals`.`animals` (
  `an_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `an_sex` ENUM('F', 'M') NOT NULL,
  `an_birth_dt` DATE NOT NULL COMMENT 'Birth date',
  `an_procedure` VARCHAR(20) NULL COMMENT 'Procedure',
  `an_loc` VARCHAR(8) NOT NULL,
  `an_rack` TINYINT NOT NULL COMMENT 'Rack',
  `an_cage` CHAR(3) NOT NULL COMMENT 'Cage	',
  `an_origin` VARCHAR(20) NOT NULL,
  `an_mother` INT UNSIGNED NULL,
  `an_father` INT UNSIGNED NULL,
  `an_death_dt` DATE NULL COMMENT 'date of death',
  `an_note` VARCHAR(1000) NULL COMMENT 'Notę',
  PRIMARY KEY (`an_id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO admin;
 DROP USER admin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'admin' IDENTIFIED BY 'wnwajwjrtz@';

GRANT ALL ON `animals`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
