-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 15:33:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema excel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `excel` ;

-- -----------------------------------------------------
-- Schema excel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `excel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `excel` ;

-- -----------------------------------------------------
-- Table `excel`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`animals` ;

CREATE TABLE IF NOT EXISTS `excel`.`animals` (
  `an_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `an_sex` ENUM('F', 'M') NOT NULL,
  `an_birth_dt` DATE NOT NULL COMMENT 'Birth date',
  `an_procedure` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Procedure',
  `an_loc` VARCHAR(8) NOT NULL,
  `an_rack` TINYINT NULL DEFAULT NULL COMMENT 'Rack',
  `an_cage` CHAR(3) NULL DEFAULT NULL COMMENT 'Cage	',
  `an_origin` VARCHAR(20) NOT NULL,
  `an_mother` INT NULL DEFAULT NULL,
  `an_mother1` INT NULL DEFAULT NULL,
  `an_mother2` INT NULL DEFAULT NULL,
  `an_father` INT NULL DEFAULT NULL,
  `an_death_dt` DATE NULL DEFAULT NULL COMMENT 'date of death',
  `an_note` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Note',
  `an_strain` VARCHAR(20) NULL DEFAULT NULL,
  `an_transgenic_line` VARCHAR(20) NULL DEFAULT NULL,
  `an_gene` VARCHAR(20) NULL DEFAULT NULL,
  `an_genotype` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`an_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excel`.`Balbc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`Balbc` ;

CREATE TABLE IF NOT EXISTS `excel`.`Balbc` (
  `an_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `an_sex` ENUM('F', 'M') NULL,
  `an_birth_dt` DATE NULL COMMENT 'Birth date',
  `an_procedure` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Procedure',
  `an_loc` VARCHAR(8) NULL,
  `an_rack` TINYINT NULL DEFAULT NULL COMMENT 'Rack',
  `an_cage` CHAR(3) NULL DEFAULT NULL COMMENT 'Cage	',
  `an_origin` VARCHAR(20) NULL,
  `an_mother` VARCHAR(20) NULL DEFAULT NULL,
  `an_father` INT NULL DEFAULT NULL,
  `an_death_dt` DATE NULL DEFAULT NULL COMMENT 'date of death',
  `an_note` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Note',
  `an_strain` VARCHAR(20) NULL DEFAULT NULL,
  `an_transgenic_line` VARCHAR(20) NULL DEFAULT NULL,
  `an_gene` VARCHAR(20) NULL DEFAULT NULL,
  `an_genotype` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`an_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excel`.`C57Bl6`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`C57Bl6` ;

CREATE TABLE IF NOT EXISTS `excel`.`C57Bl6` (
  `an_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `an_sex` ENUM('F', 'M') NULL,
  `an_birth_dt` DATE NULL COMMENT 'Birth date',
  `an_procedure` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Procedure',
  `an_loc` VARCHAR(8) NULL,
  `an_rack` TINYINT NULL DEFAULT NULL COMMENT 'Rack',
  `an_cage` CHAR(3) NULL DEFAULT NULL COMMENT 'Cage	',
  `an_origin` VARCHAR(20) NULL,
  `an_mother` VARCHAR(20) NULL DEFAULT NULL,
  `an_father` INT NULL DEFAULT NULL,
  `an_death_dt` DATE NULL DEFAULT NULL COMMENT 'date of death',
  `an_note` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Note',
  `an_strain` VARCHAR(20) NULL DEFAULT NULL,
  `an_transgenic_line` VARCHAR(20) NULL DEFAULT NULL,
  `an_gene` VARCHAR(20) NULL DEFAULT NULL,
  `an_genotype` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`an_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excel`.`Balbc_porody`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`Balbc_porody` ;

CREATE TABLE IF NOT EXISTS `excel`.`Balbc_porody` (
  `female` INT NULL DEFAULT NULL,
  `mating_nr` TINYINT NULL DEFAULT NULL,
  `mating_date` DATE NULL DEFAULT NULL,
  `male` INT NULL DEFAULT NULL,
  `plug_date` DATE NULL DEFAULT NULL,
  `pregnancy` DATE NULL DEFAULT NULL,
  `parturition` DATE NULL DEFAULT NULL,
  `nr_of_birth_pups` TINYINT NULL DEFAULT NULL,
  `weaning` DATE NULL DEFAULT NULL,
  `nr_of_F` TINYINT NULL DEFAULT NULL,
  `nr_of_M` TINYINT NULL DEFAULT NULL,
  `sum_of_pups` TINYINT NULL DEFAULT NULL,
  `comments` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excel`.`C57Bl6_porody`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`C57Bl6_porody` ;

CREATE TABLE IF NOT EXISTS `excel`.`C57Bl6_porody` (
  `female` INT NULL DEFAULT NULL,
  `mating_nr` TINYINT NULL DEFAULT NULL,
  `mating_date` DATE NULL DEFAULT NULL,
  `male` INT NULL DEFAULT NULL,
  `plug_date` DATE NULL DEFAULT NULL,
  `pregnancy` DATE NULL DEFAULT NULL,
  `parturition` DATE NULL DEFAULT NULL,
  `nr_of_birth_pups` TINYINT NULL DEFAULT NULL,
  `weaning` DATE NULL DEFAULT NULL,
  `nr_of_F` TINYINT NULL DEFAULT NULL,
  `nr_of_M` TINYINT NULL DEFAULT NULL,
  `sum_of_pups` TINYINT NULL DEFAULT NULL,
  `comments` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB;

USE `excel` ;

-- -----------------------------------------------------
-- Placeholder table for view `excel`.`vanimals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excel`.`vanimals` (`an_id` INT, `an_sex` INT, `an_birth_dt` INT, `an_procedure` INT, `an_loc` INT, `an_rack` INT, `an_cage` INT, `an_origin` INT, `an_mother` INT, `an_mother1` INT, `an_mother2` INT, `an_father` INT, `an_death_dt` INT, `an_note` INT, `an_strain` INT, `an_transgenic_line` INT, `an_gene` INT, `an_genotype` INT, `an_age` INT, `an_age_weeks` INT, `an_age_years` INT);

-- -----------------------------------------------------
-- View `excel`.`vanimals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `excel`.`vanimals`;
DROP VIEW IF EXISTS `excel`.`vanimals` ;
USE `excel`;
CREATE  OR REPLACE VIEW `vanimals` AS
SELECT *,
       DATEDIFF(NOW(), an_birth_dt) AS an_age,
       ROUND(DATEDIFF(NOW(), an_birth_dt) / 7) AS an_age_weeks,
       ROUND(DATEDIFF(NOW(), an_birth_dt) / 365.25, 1) AS an_age_years
FROM animals;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
