-- MySQL Script generated by MySQL Workbench
-- Sun Oct  1 15:28:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animals` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `animals` ;

-- -----------------------------------------------------
-- Table `animals`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animals`.`animals` ;

CREATE TABLE IF NOT EXISTS `animals`.`animals` (
  `an_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `an_sex` ENUM('F', 'M') NOT NULL,
  `an_birth_dt` DATE NOT NULL COMMENT 'Birth date',
  `an_procedure` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Procedure',
  `an_loc` VARCHAR(8) NOT NULL,
  `an_rack` TINYINT NOT NULL COMMENT 'Rack',
  `an_cage` CHAR(3) NOT NULL COMMENT 'Cage	',
  `an_origin` VARCHAR(20) NOT NULL,
  `an_mother` INT NULL DEFAULT NULL,
  `an_father` INT NULL DEFAULT NULL,
  `an_death_dt` DATE NULL DEFAULT NULL COMMENT 'date of death',
  `an_note` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Note',
  PRIMARY KEY (`an_id`))
ENGINE = InnoDB;

USE `animals` ;

-- -----------------------------------------------------
-- Placeholder table for view `animals`.`vanimals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`vanimals` (`an_id` INT, `an_sex` INT, `an_birth_dt` INT, `an_procedure` INT, `an_loc` INT, `an_rack` INT, `an_cage` INT, `an_origin` INT, `an_mother` INT, `an_father` INT, `an_death_dt` INT, `an_note` INT, `an_age` INT, `an_age_weeks` INT, `an_age_years` INT);

-- -----------------------------------------------------
-- View `animals`.`vanimals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animals`.`vanimals`;
DROP VIEW IF EXISTS `animals`.`vanimals` ;
USE `animals`;
CREATE  OR REPLACE VIEW `vanimals` AS
SELECT *,
       DATEDIFF(NOW(), an_birth_dt) AS an_age,
       ROUND(DATEDIFF(NOW(), an_birth_dt) / 7) AS an_age_weeks,
       ROUND(DATEDIFF(NOW(), an_birth_dt) / 365.25, 1) AS an_age_years
FROM animals;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
